#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE_TAG="$2"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG); FILE_ROOT="$DOKKU_ROOT/$APP/DOKKU_FILES"
verify_app_name "$APP"

dokku_log_info1 "Adding remote registry tag"
/usr/bin/docker tag dokku/sbwidgets seh-docker-reg.3db.local:5000/sbwidgets:latest

dokku_log_verbose "Pushing image to registry"
/usr/bin/docker push seh-docker-reg.3db.local:5000/sbwidgets:latest
